<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>WorriorNotes</AssemblyName>
    <RootNamespace>WorriorNotes.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.Blazor" Version="4.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorriorNotes.Infrastructure\WorriorNotes.Infrastructure.csproj" />
    <ProjectReference Include="..\WorriorNotes.UI\WorriorNotes.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
