<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>WorriorVex</AssemblyName>
    <RootNamespace>WorriorVex.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.Blazor" Version="4.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorriorVex.Infrastructure\WorriorVex.Infrastructure.csproj" />
    <ProjectReference Include="..\WorriorVex.UI\WorriorVex.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
